version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn
          working_directory: frontend
      - run:
          name: yarn build
          command: yarn build-prod
          working_directory: frontend
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    working_directory: ~/work
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - gcp-cli/initialize
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud --quiet app deploy app.yaml

workflows:
  version: 2.0
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master